// <auto-generated />
using Bulky.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230622110854_addedImageUrl")]
    partial class addedImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bulky.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 3,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 5,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 1,
                            Name = "Crime"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ListPrice")
                        .HasColumnType("real");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<float>("Price100")
                        .HasColumnType("real");

                    b.Property<float>("Price50")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthurName = "Gideon",
                            CategoryId = 2,
                            Description = "a book written by Oknko Chibodzor",
                            ISBN = "SNG234JUT34",
                            ImageUrl = "",
                            ListPrice = 45f,
                            Price = 34f,
                            Price100 = 56f,
                            Price50 = 89f,
                            Title = "All that Glitters"
                        },
                        new
                        {
                            Id = 2,
                            AuthurName = "Gideon",
                            CategoryId = 2,
                            Description = "a book written by Oknko Chibodzor",
                            ISBN = "HG985652LN",
                            ImageUrl = "",
                            ListPrice = 45f,
                            Price = 34f,
                            Price100 = 56f,
                            Price50 = 89f,
                            Title = "Amen to all Prayers"
                        },
                        new
                        {
                            Id = 3,
                            AuthurName = "Gideon",
                            CategoryId = 2,
                            Description = "There is a land that is farer than the day!",
                            ISBN = "JI87541256DS",
                            ImageUrl = "",
                            ListPrice = 45f,
                            Price = 34f,
                            Price100 = 56f,
                            Price50 = 89f,
                            Title = "A charge to keep I have"
                        },
                        new
                        {
                            Id = 4,
                            AuthurName = "Gideon",
                            CategoryId = 2,
                            Description = "With God, all things are possible",
                            ISBN = "BN568452SD",
                            ImageUrl = "",
                            ListPrice = 45f,
                            Price = 34f,
                            Price100 = 56f,
                            Price50 = 89f,
                            Title = "Redeemer Lives"
                        },
                        new
                        {
                            Id = 5,
                            AuthurName = "Gideon",
                            CategoryId = 2,
                            Description = "a book written by Oknko Chibodzor",
                            ISBN = "MN7585212SW",
                            ImageUrl = "",
                            ListPrice = 45f,
                            Price = 34f,
                            Price100 = 56f,
                            Price50 = 89f,
                            Title = "All Oddss"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Product", b =>
                {
                    b.HasOne("Bulky.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
